### ISSUE TITLE
Facebook ads

### ISSUE THREAD

**Issue by SeriousHoax** [Yuki2718/adblock#63]
### URL(s) where the issue occurs (mandatory) / 問題のURL（必須）

Full URL / 完全なURL: https://www.facebook.com/

### Describe the issue (mandatory) / 何が問題か説明してください（必須）

Hello Yuki. I was wondering why these Sponsered contents and other facebook ads can't be blocked by uBlock Origin using EasyList and Adguard filters while the Adguard extension can block them just fine. Adguard only can't block video ads but the rest it can. Why is it not possible for uBlock Origin to do it? 
There are often posts like this on Reddit with temporary solutions that doesn't work anymore after a few days.
https://www.reddit.com/r/uBlockOrigin/comments/vzt0bd/facebook_sponsored_ads_appear_again/

Can you explain if you don't mind and do you have any solutions?

### Screenshot(s) / スクリーンショット

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29574622/184318421-e1728342-e9e5-441d-bd55-ee487389ebdf.png)
</details>

### Versions (mandatory) / バージョン情報（必須）

- Operating system and version / OSの種類とバージョン: Windows 11
- Browser and version / ブラウザの種類とバージョン: Chrome, Edge, Firefox
- AdGuard or uBlock Origin version / AdGuardないしuBlock Originのバージョン: uBlock Origin latest version 1.43.0

### Filters (mandatory) / 使用フィルタ（必須）

uBlock Origin Default + ADGBase, ADG Tracking, ADG Annoyance, ADG Social.

**Comment by Yuki2718** [comment]
FIrst of all I'm not really a FB user. The main reason is that AG uses vanilla script filters like `https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/general_extensions.txt#L2867` which works only on AG. If one wants to use these filters on uBO the only way will be setting userResourcesLocation, adding them into your own resources location, and updating by yourself every time the filters are updated - not easier than using any of user script manger such as Violentmonkey. The vanilla script is certainly useful to tackle serious circumventor including FB and we had internal dicussion about this in past. A problem is Firefox (and Opera) doesn't allow executing remote JS, AG is no exception and thus those script filters in AG Firefox/Opera Ext. can only be updated when the extension themselves are updated while AG apps and Chrome Ext. can update them soon after updates in upstream lists. By this restriction, to uBO it's not far different from adding another scriptlet like anti-fb-ad.js which itself would need frequent update as in the script filters in AG list - not a trivial workload. Since FB has clearly been trying to bypass blocker, uBO currently lets Reddit community to address FB ads, the latest thread (probably you know) is `https://www.reddit.com/r/uBlockOrigin/comments/wjqvz6/ads_are_back_again_on_facebook_looks_like_they/` and accroding to it "Sep'21 idea / October update" in wiki may work `facebook.com##[role="feed"] span[id] a[href="#"]:not(:has-text(/(\s|\d|^$)/)):upward([role="feed"]>div, [role="feed"]>span)` . But if these filters were added to Built-in lists, FB would counter them sooner.

**Comment by SeriousHoax** [comment]
Thanks for the very detailed explanation. Now it's clear to me. So my best bet is to use Adguard which I like a lot anyway and on the other hand facebook sponsored ads aren't too much of an annoyance, actually. Video ads are bad, but it's not possible to block them. So I can keep using uBO if I want. 
Ultimately, manifest V3 will decide which adblocker I'll use in the long run. 
Thanks, it has been helpful.
