### ISSUE TITLE
Possible typo at jpf-plus

### ISSUE THREAD

**Issue by RicoHeat** [Yuki2718/adblock#68]
I'm not sure if it was a mistake.. Just wanted to be on the safe side..

https://github.com/Yuki2718/adblock/blob/master/adguard/jpf-plus.txt

At the bottom of the list.. 

!#if adguard
!#include jpfp-adguard.txt
!#endif
!#if !adguard     ⬅️  Maybe its supposed to be !#if  uBlock??
!#include jpfp-ublock.txt
!#endif

**Comment by Yuki2718** [comment]
Actually this is okay -  `!#if` arguments have either `true` or `false` value and adding `!` reverses that. So `!#if !adguard` means "Any environment not Adguard (including uBlock Origin)".  At the time of the change, I was not sure if `ext_ublock` is true or false on uBlock Origin Lite and this is why I used `!adguard`. But now it [turned out](https://github.com/uBlockOrigin/uBOL-issues/issues/1#issuecomment-1271544019) `ext_ublock` is true on uBOL too, I will revert to ext_ublock`.

**Comment by RicoHeat** [comment]
Pretty cool.. I'm just trying to learn and at the same time help whenever I can.. Good day my friend! 👍
