### ISSUE TITLE
not an issue- wordpress plugin list

### ISSUE THREAD

**Issue by jawz101** [Yuki2718/adblock#8]
I just wanted to comment because I came across your static rules list on filterlists.com that mentions Wordpress plugins.  I took the opposite approach and have a global deny rule on that directory on any site and then whitelist as I encounter breakage.

https://github.com/jawz101/ublockOrigin_wordpressWhitelist

specific [blocklist file link](https://raw.githubusercontent.com/jawz101/ublockOrigin_wordpressWhitelist/master/my-ublock-static-filters_wordpressWhitelist.txt)

I just wanted to pass it along.

**Comment by Yuki2718** [comment]
@jawz101 Thank you for informing. Yeah, that is a more secure approach and I'm glad to see a fellow trying to tackle the same issue. Your list looks good, I'll mention yours in my README for those who want stronger protection later today when I update other lists.

**Comment by jawz101** [comment]
If you ever want to try that route we can always team up to add exceptions.
I've never spoken up about it on reddit or anything but it's nice to find someone who had the same thought

**Comment by Yuki2718** [comment]
Well, personally I won't despite being aware that blacklisting is like a Swiss cheese, since "do only one thing at a time" is my first principle - I don't want to mess in contents blocking on regular browsing, this is why I dropped uMatrix and taking dedicated time for contents blocking nearly every day.  However, probably we can occasionally help each other by providing info. As a first step, I remember I made an exception for `/wp-content/plugins/arscode-ninja-popups/*$~image` to allow image - but unfortunately the original blog the problem arose (`photoshoptutorials.ws`) now doesn't use this plugin any more. So I'm now searching for another case at themesinfo `https://themesinfo.com/wordpress-plugins` but so far can't find the problem - only found a blog calling font for this plugin (`www.marblearch-inn.co.uk`) but not image. I'll try tomorrow. Now closing but you can of course keep commenting in this issue.
